create table person
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(50) not null,
    yearOfBirthday int not null
);

create table book
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(50) not null,
    author varchar(50) not null,
    year int not null,
    person_id int references person(id)
);

insert into person(fio, yearOfBirthday) VALUES ('Иванов Иван Иванович', 1970);
insert into person(fio, yearOfBirthday) VALUES ('Петро Петр Петрович', 1960);
insert into person(fio, yearOfBirthday) VALUES ('Алексеев Алексей Алексеевич', 1989);
insert into person(fio, yearOfBirthday) VALUES ('Познер Владимир Владимирович', 1944);
insert into person(fio, yearOfBirthday) VALUES ('Федоров Мирон Янович', 1985);

insert into book(title, author, year) VALUES ('День опричника', 'Владимир Сорокин', 2006);
insert into book(title, author, year) VALUES ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
insert into book(title, author, year) VALUES ('Философия Java', 'Брюс Эккель', 2018);
insert into book(title, author, year) VALUES ('Психопатология обыденной жизни', 'Зигмунд Фрейд', 1904);